version: '3.8'

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

volumes:
  postgres_volume: