[project]
name = "capybara-api"
version = "0.1.0"
description = "capybara-api"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "orjson>=3.10.16",
    "uvicorn>=0.34.1",
]
