# Generated by Django 5.0.3 on 2024-06-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='person',
            name='modified',
        ),
        migrations.AddField(
            model_name='filmwork',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='измененный'),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='измененный'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='измененный'),
        ),
    ]
