repos:
- repo: https://github.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
    - id: flake8
      name: Run linter
      args: [--config, .flake8]
      additional_dependencies: [
        pep8-naming,
        flake8-django
      ]
      verbose: true
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: Run isort
      alias: isort -qc .
