version: '3'

services:

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

  api:
    build:
      context: ./services/pastebin_api
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - "POSTGRES_DB=db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"