version: '3.8'

services:

  movies_api:
    restart: always
    build: .
    command: >
      sh -c "cd /app/src/
      && python main.py"
    volumes:
      - .:/app
    env_file:
      - ${ENV}
    ports:
      - "8080:8080"

  elastic:
    image: elasticsearch:8.13.0
    expose:
      - 9200
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - ${ENV}
    ports:
      - "6380:6379"
