version: '3.8'

services:

  admin_panel:
    restart: always
    build: ../..
    command: >
      sh -c "cd /app/src/
      && python manage.py migrate --noinput
      && python manage.py createsuperuser --noinput || true
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../..:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - "DJANGO_SUPERUSER_USERNAME=admin"
      - "DJANGO_SUPERUSER_EMAIL=admin@gmail.com"
      - "DJANGO_SUPERUSER_PASSWORD=root"
      - "MOVIES_ADMIN_SECRET_KEY=secretkey"
      - "MOVIES_ADMIN_DEBUG=True"
      - "MOVIES_DB_NAME=postgres"
      - "MOVIES_DB_USER=postgres"
      - "MOVIES_DB_PASSWORD=postgres"
      - "MOVIES_DB_HOST=movies_db"
      - "MOVIES_DB_PORT=5432"
    depends_on:
      - movies_db

  movies_db:
    build: ../../infra/postgres/
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
        - movies_db_volume:/var/lib/postgresql/data/

volumes:
  movies_db_volume: