# Generated by Django 4.2.7 on 2023-11-07 15:41

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=events.models.get_event_image_upload_path, verbose_name='изображение предварительного просмотра мероприятия')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название мероприятия')),
                ('slug', models.SlugField(unique=True, verbose_name='url мероприятия')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='описание мероприятия')),
                ('maximum_number_of_event_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='максимальное количество участников мероприятия')),
                ('maximum_commands', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='максимальное количество команд')),
                ('maximum_commands_per_class', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='максимальное количество команд от класса')),
                ('maximum_number_of_team_members', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='максимальное количество участников в команде')),
                ('minimum_number_of_team_members', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='минимальное количество участников в команде')),
                ('status', models.CharField(blank=True, choices=[('Ожидание регистрации', 'Registration Pending'), ('Регистрация открыта', 'Registration Open'), ('В процессе', 'Ongoing'), ('Завершено', 'Completed'), ('Отменено', 'Cancelled'), ('Отложено', 'Postponed')], max_length=50, verbose_name='статус мероприятия')),
                ('type', models.CharField(blank=True, choices=[('Индивидуальное', 'Individual'), ('Командное', 'Team'), ('Командное от классов', 'Class Teams')], max_length=50, verbose_name='тип мероприятия')),
                ('date_of_ending_registration', models.DateField(verbose_name='дата окончания регистрации')),
                ('date_of_starting_registration', models.DateField(verbose_name='дата начала регистрации')),
                ('date_of_starting_event', models.DateField(verbose_name='дата начала мероприятия')),
                ('is_draft', models.BooleanField(blank=True, default=False, verbose_name='черновик')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', verbose_name='мероприятие')),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название команды')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event', verbose_name='мероприятие')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('1 место', 'First Place'), ('2 место', 'Second Place'), ('3 место', 'Third Place'), ('Призёр', 'Prize Winner'), ('Победитель', 'Winner'), ('Лауреат', 'Laureate'), ('Участник', 'Participant'), ('Дипломат', 'Diplomat')], default='Участник', max_length=20, verbose_name='место')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.event', verbose_name='мероприятие')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.participant', verbose_name='участник')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.team', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='events.team', verbose_name='команда'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom', models.FileField(blank=True, null=True, upload_to=events.models.event_diplom_path, verbose_name='диплом')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='events.event', verbose_name='мероприятие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='events.participant', verbose_name='участник')),
            ],
            options={
                'verbose_name': 'диплом',
                'verbose_name_plural': 'дипломы',
            },
        ),
    ]
