# Generated by Django 4.2.7 on 2023-11-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(blank=True, default=False, verbose_name='опубликованные'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='url мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('Ожидание регистрации', 'Ожидание регистрации'), ('Регистрация открыта', 'Регистрация открыта'), ('В процессе', 'В процессе'), ('Завершено', 'Завершено'), ('Отменено', 'Отменено'), ('Отложено', 'Отложено')], max_length=50, verbose_name='статус мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Индивидуальное', 'Индивидуальное'), ('Командное', 'Командное'), ('Командное от классов', 'Командное от классов')], max_length=50, verbose_name='тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(blank=True, choices=[('1 место', '1 место'), ('2 место', '2 место'), ('3 место', '3 место'), ('Призёр', 'Призёр'), ('Победитель', 'Победитель'), ('Лауреат', 'Лауреат'), ('Участник', 'Участник'), ('Дипломат', 'Дипломат')], default='Участник', max_length=20, verbose_name='место'),
        ),
    ]
