# Generated by Django 4.2.7 on 2023-11-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_is_draft_event_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForEventField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='ярлык')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('file', 'File'), ('float', 'Float'), ('char', 'Char')], default='text', max_length=20, verbose_name='тип поля')),
                ('is_blank', models.BooleanField(default=True, verbose_name='является ли поле обязательным')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='мероприятие')),
            ],
            options={
                'verbose_name': 'поле для формы регистрации на мероприятие',
                'verbose_name_plural': 'поля для формы регистрации на мероприятие',
            },
        ),
    ]
