version: '3.8'

services:
  backend:
    build: ./chat_api
    command: python chat_api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    expose:
      - 8000
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
