# Generated by Django 4.2.4 on 2023-10-28 09:22

import competitions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom', models.FileField(blank=True, null=True, upload_to=competitions.models.competition_diplom_path, verbose_name='диплом')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.participant', verbose_name='участник')),
            ],
            options={
                'verbose_name': 'награда',
                'verbose_name_plural': 'награды',
            },
        ),
    ]
