# Generated by Django 4.2.6 on 2023-10-29 18:37

import competitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=competitions.models.get_competition_image_upload_path, verbose_name='изображение'),
        ),
    ]
