# Generated by Django 4.2.4 on 2023-10-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_participant_result_reward_result_team_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='competition',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='competitions.competition', verbose_name='конкурс'),
            preserve_default=False,
        ),
    ]
