services:

  app:
    container_name: app
    restart: always
    build: .
    command: >
      sh -c "cd /app/src/ && uv run main.py"
    expose:
      - "8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST=db"
      - "POSTGRES_PORT=5432"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
        - db_volume:/var/lib/postgresql/data/

volumes:
  db_volume:
